# Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
# This product includes software developed at Datadog (https://www.datadoghq.com/) Copyright 2025 Datadog, Inc.

source 'https://rubygems.org'

# The tracer instruments the app through a railtie, so this has to be a Rails
# app. railties + actionpack is the smallest set that provides one.
gem 'railties', '~> 8.1'
gem 'actionpack', '~> 8.1'
gem 'puma', '~> 8.0'
