name: Terraform Docs Check

permissions:
  contents: read

on:
  pull_request:
    paths:
      - "**"

jobs:
  terraform-docs:
    name: Check terraform-docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install terraform-docs
        run: |
          VERSION="v0.20.0"
          OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          ARCH=$(uname -m)
          if [ "$ARCH" = "x86_64" ]; then ARCH="amd64"; fi
          URL="https://github.com/terraform-docs/terraform-docs/releases/download/${VERSION}/terraform-docs-${VERSION}-${OS}-${ARCH}.tar.gz"
          echo "Downloading terraform-docs from $URL"
          curl -sSLo terraform-docs.tar.gz "$URL"
          tar -xzf terraform-docs.tar.gz terraform-docs
          chmod +x terraform-docs
          sudo mv terraform-docs /usr/local/bin/

      - name: Check Docs are up to date
        run: |
          terraform-docs . --output-check --config .terraform-docs.yml
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo 'Terraform docs are not up to date. Please run `pre-commit run --all-files` to fix.'
          fi
          exit $exit_code
